export const API_MODULES = {
  AUTH: '/auth',
  USERS: '/users',
  PAYMENT: '/payment',
  STORAGE: '/storage',
  SCM: '/scm',
  FINANCE: '/finance',
  MAIL: '/mail',
  SALES: '/sales',
};

const MENU_BASE = '/menu';
const RULE_BASE = '/securityrule';
const GROUP_BASE = '/securitygroup';
const COMBO_BASE = '/combo';
const SYSTEM_VARIABLE_BASE = '/systemvariable';
const COMPANY_BASE = '/company';
const COMMON_BASE = '/common';
const AUDIT_LOG_BASE = '/auditlog';
const SECURITY_CACHE_BASE = '/SecurityCache';

export const API_ENDPOINTS = {
  SYSTEM_CONFIGURATION: {
    GET: (companyId: string) => `/systemconfiguration/get/${companyId}`,
    SAVE: '/systemconfiguration/save-system-configuration',
  },
  MENU: {
    GET_ALL: `${MENU_BASE}/get-all`,
    GET_BY_TYPE: (type: string) => `${MENU_BASE}/get-by-menu-type/${type}`,
    GET_BY_TYPE_AND_COMPANY: (type: string, companyId: string) => `${MENU_BASE}/get-by-menu-type/${type}/${companyId}`,
    SAVE: `${MENU_BASE}/save`,
    REORDER: `${MENU_BASE}/reorder`,
    DELETE: `${MENU_BASE}/delete`,
    GET_LAST_ID: `${MENU_BASE}/get-last-menuid`,
    GET_API_PATH: (id: number) => `${MENU_BASE}/get-api-path/${id}`,
    GET_LOGIN_MENUS: `${MENU_BASE}/get-login-menus`,
    COPY: `${MENU_BASE}/copy`,
  },
  SECURITY_RULE: {
    GET_GRID: `${RULE_BASE}/get-grid-data`,
    GET_GRID_SUPER: `${RULE_BASE}/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `${RULE_BASE}/get/${id}`,
    SAVE: `${RULE_BASE}/save`,
    SAVE_SUPER: `${RULE_BASE}/save-super`,
    GET_PERMISSIONS: (id: number | string) => `${RULE_BASE}/get-permission-list/${id}`,
    // Function returning string for superuser permissions
    GET_PERMISSIONS_SUPER: (id: number | string, companyId: string) => `${RULE_BASE}/get-permission-list-super/${id}/${companyId}`,
    DELETE: (id: number | string) => `${RULE_BASE}/delete/${id}`,
  },
  SECURITY_GROUP: {
    GET_GRID: `${GROUP_BASE}/get-grid-data`,
    GET_GRID_SUPER: `${GROUP_BASE}/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `${GROUP_BASE}/get/${id}`,
    SAVE: `${GROUP_BASE}/save`,
    SAVE_SUPER: `${GROUP_BASE}/save-super`,
    DELETE: (id: number | string) => `${GROUP_BASE}/delete/${id}`
  },
  COMBO: {
    GET_RULES: `${COMBO_BASE}/get-rules`,
    GET_GROUPS: `${COMBO_BASE}/get-groups`,
    GET_RULES_SUPER: (companyId: string) => `${COMBO_BASE}/get-rules-super/${companyId}`,
    GET_GROUPS_SUPER: (companyId: string) => `${COMBO_BASE}/get-groups-super/${companyId}`,
    GET_COMPANIES: `${COMBO_BASE}/get-companies`,
    GET_PARENT_COMPANIES: `${COMBO_BASE}/get-parent-company`,
    GET_ALL_COMPANIES: `${COMBO_BASE}/get-all-company`,
    GET_SYSTEM_VARIABLES: (category: string) => `${COMBO_BASE}/get-systemvariables/${category}`,
    GET_DEFAULT_MENUS: `${COMBO_BASE}/get-default-menus`,
    GET_DEFAULT_MENUS_SUPER: (companyId: string) => `${COMBO_BASE}/get-default-menus-super/${companyId}`,
    GET_DIVISIONS: `${COMBO_BASE}/get-division`,
    GET_DIVISIONS_SUPER: `${COMBO_BASE}/get-division-super`,
    GET_DISTRICTS: `${COMBO_BASE}/get-district`,
    GET_DISTRICTS_SUPER: `${COMBO_BASE}/get-district-super`,
    GET_DISTRICTS_BY_DIVISION: (divisionId: string | number) => `${COMBO_BASE}/get-district-by-division/${divisionId}`,
    GET_THANAS: `${COMBO_BASE}/get-thana`,
    GET_THANAS_SUPER: `${COMBO_BASE}/get-thana-super`,
    GET_THANAS_BY_DISTRICT: (districtId: string | number) => `${COMBO_BASE}/get-thana-by-district/${districtId}`,
    GET_USER_TYPES: `${COMBO_BASE}/get-user-type`,
    GET_PERSONS: `${COMBO_BASE}/get-persons`,
    GET_STAKEHOLDER_LOCATION: (stakeholderId: number | string) => `${COMBO_BASE}/get-stakeholder-location/${stakeholderId}`,
    GET_DEALERS: `${COMBO_BASE}/get-dealers`,
    GET_DSRS: `${COMBO_BASE}/get-dsrs`,
    GET_DSRS_BY_DEALER: (dealerId: number | string) => `${COMBO_BASE}/get-dsrs-by-dealer/${dealerId}`,
    GET_AGENTS_BY_DEALER: (dealerId: number | string) => `${COMBO_BASE}/get-agents-by-dealer/${dealerId}`,
    GET_DEALERS_BY_COMPANY: (companyId: number | string) => `${COMBO_BASE}/get-dealers-by-company/${companyId}`,
    GET_DEALER_MEMBERS: (dealerId: number | string) => `${COMBO_BASE}/get-dealer-members/${dealerId}`,
  },
  COMPANY: {
    GET_GRID: `${COMPANY_BASE}/get-grid-data`,
    GET_BY_ID: (id: number | string) => `${COMPANY_BASE}/get/${id}`,
    SAVE: `${COMPANY_BASE}/save`,
    DELETE: (id: number | string) => `${COMPANY_BASE}/delete/${id}`,
    GET_COMBO: `${COMPANY_BASE}/get-combo`,
  },
  USER: {
    GET_GRID: `/user/get-grid-data`,
    GET_GRID_SUPER: `/user/get-grid-data-super`,
    GET_BY_ID: `/user/get-user`,
    GET_BY_ID_SUPER: `/user/get-user-super`,
    SAVE: `/user/register`,
    CREATE_SUPER: `/user/create-user`,
    CHANGE_PASSWORD: `/user/change-password`,
    DELETE: (id: number | string) => `/user/delete/${id}`,
    MAP_USER_AND_PERSON: `/user/map-user-and-person`,
  },
  SYSTEM_VARIABLE: {
    GET_GRID: `${SYSTEM_VARIABLE_BASE}/get-grid-data`,
    GET_GRID_SUPER: `${SYSTEM_VARIABLE_BASE}/get-grid-data-super`,
    SAVE: `${SYSTEM_VARIABLE_BASE}/save`,
    SAVE_SUPER: `${SYSTEM_VARIABLE_BASE}/save-super`,
    DELETE: (id: number | string) => `${SYSTEM_VARIABLE_BASE}/delete/${id}`,
  },
  DIVISION: {
    GET_GRID: `/division/get-grid-data`,
    GET_GRID_SUPER: `/division/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/division/get/${id}`,
    SAVE: `/division/save`,
    DELETE: (id: number | string) => `/division/delete/${id}`,
  },
  DISTRICT: {
    GET_GRID: `/district/get-grid-data`,
    GET_GRID_SUPER: `/district/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/district/get/${id}`,
    SAVE: `/district/save`,
    DELETE: (id: number | string) => `/district/delete/${id}`,
  },
  THANA: {
    GET_GRID: `/thana/get-grid-data`,
    GET_GRID_SUPER: `/thana/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/thana/get/${id}`,
    SAVE: `/thana/save`,
    DELETE: (id: number | string) => `/thana/delete/${id}`,
  },
  COMMON: {
    GET_USER_LOG_GRID: `${COMMON_BASE}/get-user-log-grid-data`,
    GET_USER_LOG_GRID_SUPER: `${COMMON_BASE}/get-user-log-grid-data-super`,
  },
  AUDIT_LOG: {
    GET_SYSTEM_CONFIG: (id: number | string, dataSize?: number) => `${AUDIT_LOG_BASE}/get-system-config-audit/${id}${dataSize ? `/${dataSize}` : ''}`
  },
  SECURITY_CACHE: {
    SUMMARY: `${SECURITY_CACHE_BASE}/summary`,
    LIST: (entityType: string) => `${SECURITY_CACHE_BASE}/${entityType}/list`,
    GET_BY_ID: (entityType: string, id: string | number) => `${SECURITY_CACHE_BASE}/${entityType}/${id}`,
    CLEAR: (entityType: string) => `${SECURITY_CACHE_BASE}/${entityType}/clear`,
    EVICT: (entityType: string, id: string | number) => `${SECURITY_CACHE_BASE}/${entityType}/${id}/evict`,
    RELOAD: (entityType: string) => `${SECURITY_CACHE_BASE}/${entityType}/reload`,
  },
  KYC: {
    OCR: '/kyc/ocr',
    SUBMIT: '/kyc/submit',
  },
  GLOBAL_SETTING: {
    ALL: '/global-setting/all',
    GET: (key: string) => `/global-setting/${key}`,
    SAVE: '/global-setting/save',
  },
  USER_SETTING: {
    GET: (userId: number, key: string) => `/user-setting/${userId}/${key}`,
    SAVE: '/user-setting/save',
  },
  STORAGE: {
    UPLOAD: '/Storage/upload',
    DOWNLOAD: (fileKey: string) => `/Storage/download/${fileKey}`,
    DELETE: (fileKey: string) => `/Storage/delete/${fileKey}`,
  },
  WAREHOUSE: {
    GET_GRID: `/warehouse/get-grid-data`,
    GET_GRID_SUPER: `/warehouse/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/warehouse/get/${id}`,
    SAVE: `/warehouse/save`,
    SAVE_SUPER: `/warehouse/save-super`,
    DELETE: (id: number | string) => `/warehouse/delete/${id}`,
  },
  CATEGORY: {
    GET_GRID: `/product/get-category-grid-data`,
    GET_GRID_SUPER: `/product/get-category-grid-data-super`,
    GET_ALL: `/product/get-all-categories`,
    GET_COMBO: `/product/get-category-combo`,
    GET_BY_ID: (id: number | string) => `/product/get-category/${id}`,
    SAVE: `/product/save-category`,
    SAVE_SUPER: `/product/save-category-super`,
    DELETE: (id: number | string) => `/product/delete-category/${id}`,
  },
  BRAND: {
    GET_GRID: `/brand/get-grid-data`,
    GET_COMBO: `/brand/get-combo`,
    GET_BY_ID: (id: number | string) => `/brand/get/${id}`,
    SAVE: `/brand/save`,
    DELETE: (id: number | string) => `/brand/delete/${id}`,
  },
  UNIT: {
    GET_GRID: `/unit/get-grid-data`,
    GET_COMBO: `/combo/get-unit-combo`,
    GET_BY_ID: (id: number | string) => `/unit/get/${id}`,
    SAVE: `/unit/save`,
    DELETE: (id: number | string) => `/unit/delete/${id}`,
  },
  PRODUCT: {
    GET_GRID: `/product/get-grid-data`,
    GET_GRID_SUPER: `/product/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/product/get/${id}`,
    SAVE: `/product/save`,
    SAVE_WITH_FILES: `/product/save-with-files`,
    CSV_UPLOAD: `/product/csv-upload`,
    DELETE: (id: number | string) => `/product/delete/${id}`,
    GET_ALL: `/product/get-all`,
  },
  PRODUCT_ATTRIBUTE: {
    GET_COMBO: `/combo/get-attribute-combo`,
    SAVE: `/product/save-attribute`,
    GET_VALUES: (productId: number | string) => `/product/get-attribute-values/${productId}`,
    SAVE_VALUES: `/product/save-attribute-values`,
  },
  PURCHASE_REQUISITION: {
    GET_GRID: `/purchaserequisition/get-grid-data`,
    GET_GRID_SUPER: `/purchaserequisition/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/purchaserequisition/get/${id}`,
    SAVE: `/purchaserequisition/save`,
    DELETE: (id: number | string) => `/purchaserequisition/delete/${id}`,
  },
  PURCHASE_QUOTATION: {
    GET_GRID: `/purchasequotation/get-grid-data`,
    GET_GRID_SUPER: `/purchasequotation/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/purchasequotation/get/${id}`,
    GET_BY_REQUISITION: (reqId: number | string) => `/purchasequotation/get-by-requisition/${reqId}`,
    SAVE: `/purchasequotation/save`,
    DELETE: (id: number | string) => `/purchasequotation/delete/${id}`,
  },
  GOODS_RECEIPT: {
    GET_GRID: `/goodsreceipt/get-grid-data`,
    GET_GRID_SUPER: `/goodsreceipt/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/goodsreceipt/get/${id}`,
    SAVE: `/goodsreceipt/save`,
    DELETE: (id: number | string) => `/goodsreceipt/delete/${id}`,
  },
  SALES: {
    GET_GRID: `/sales/get-grid-data`,
    GET_GRID_SUPER: `/sales/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/sales/get/${id}`,
    SAVE: `/sales/save`,
    DELETE: (id: number | string) => `/sales/delete/${id}`,
  },
  PURCHASE_ORDER: {
    GET_GRID: `/purchaseorder/get-grid-data`,
    GET_GRID_SUPER: `/purchaseorder/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/purchaseorder/get/${id}`,
    GET_BY_QUOTATION: (qId: number | string) => `/purchaseorder/get-by-quotation/${qId}`,
    SAVE: `/purchaseorder/save`,
    DELETE: (id: number | string) => `/purchaseorder/delete/${id}`,
  },
  SUPPLIER: {
    GET_GRID: `/supplier/get-grid-data`,
    GET_GRID_SUPER: `/supplier/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/supplier/get/${id}`,
    SAVE: `/supplier/save`,
    DELETE: (id: number | string) => `/supplier/delete/${id}`,
  },
  FINANCE_COA: {
    GET_COMBO: (type: string) => `/chartofaccounts/get-combo?type=${type}&isTransactional=true`,
  },
  MAIL_CONFIGURATION: {
    SAVE: `/mailconfiguration/save`,
    GET_ACTIVE: `/mailconfiguration/get-active`,
    GET_BY_ID: (id: number | string) => `/mailconfiguration/get/${id}`,
    GET_GRID: `/mailconfiguration/get-grid-data`,
    GET_GRID_SUPER: `/mailconfiguration/get-grid-data-super`,
    GET_ALL: `/mailconfiguration/get-all`,
    DELETE: (id: number | string) => `/mailconfiguration/delete/${id}`,
  },
  MAIL_GROUP_SETUP: {
    SAVE: `/mailgroupsetup/save`,
    GET_BY_ID: (id: number | string) => `/mailgroupsetup/get/${id}`,
    GET_GRID: `/mailgroupsetup/get-grid-data`,
    GET_GRID_SUPER: `/mailgroupsetup/get-grid-data-super`,
    GET_ALL: `/mailgroupsetup/get-all`,
    GET_BY_NAME: (name: string) => `/mailgroupsetup/get-by-name/${name}`,
    DELETE: (id: number | string) => `/mailgroupsetup/delete/${id}`,
  },
  MAIL_LOG: {
    ENQUEUE: `/maillog/enqueue`,
    GET_BY_ID: (id: number | string) => `/maillog/${id}`,
    GET_ALL: `/maillog`,
    RETRY: (id: number | string) => `/maillog/retry/${id}`,
    GET_GRID: `/maillog/get-grid-data`,
    GET_GRID_SUPER: `/maillog/get-grid-data-super`,
  },
  MAIL_TEMPLATE: {
    SAVE: `/mailtemplate/save`,
    GET_BY_ID: (id: number | string) => `/mailtemplate/get/${id}`,
    GET_BY_GROUP: (groupId: number | string) => `/mailtemplate/get-by-group/${groupId}`,
    GET_ALL: `/mailtemplate/get-all`,
    DELETE: (id: number | string) => `/mailtemplate/delete/${id}`,
    SEND_TEST: `/mailtemplate/send-test`,
  },
  VISIT_PLAN_TEMPLATE: {
    GET_GRID: `/visitplan/template-get-grid-data`,
    GET_GRID_SUPER: `/visitplan/template-get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/visitplan/template-get/${id}`,
    SAVE: `/visitplan/template-save`,
    SAVE_SUPER: `/visitplan/super-template-save`,
    DELETE: (id: number | string) => `/visitplan/template-delete/${id}`,
    DELETE_SUPER: (id: number | string) => `/visitplan/super-template-delete/${id}`,
    GENERATE_PLAN: `/visitplan/template-generate-plan`,
    GET_DSR_SCHEDULE: (dsrUserId: number | string, date: string) => `/visitplan/template-get-dsr-schedule?dsrUserId=${dsrUserId}&date=${date}`,
    GET_DEALER_ROADMAP: (dealerId: number | string, date: string) => `/visitplan/template-get-dealer-roadmap?dealerId=${dealerId}&date=${date}`,
  },
  VISIT_PLAN: {
    GET_GRID: `/visitplan/get-grid-data`,
    GET_GRID_SUPER: `/visitplan/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/visitplan/get/${id}`,
    SAVE: `/visitplan/save`,
    DELETE: (id: number | string) => `/visitplan/delete/${id}`,
    ACTIVATE: (id: number | string) => `/visitplan/activate/${id}`,
    COMPLETE: (id: number | string) => `/visitplan/complete/${id}`,
    CANCEL: (id: number | string) => `/visitplan/cancel/${id}`,
    SUBMIT: `/visitplan/submit`,
    VERIFY: (id: number | string) => `/visitplan/verify/${id}`,
    REJECT: (id: number | string) => `/visitplan/reject/${id}`,
    GET_VISIT_REPORT: `/visitplan/get-visit-report`,
    GET_VISIT_REPORT_SUPER: `/visitplan/get-visit-report-super`,
    DEALER_SUMMARY: (dealerId: number | string, companyId: number | string) => `/visitplan/dealer-summary/${dealerId}/${companyId}`,
  },
  FINANCE_COA_CRUD: {
    GET_GRID: '/chartofaccounts/get-grid-data',
    SAVE: '/chartofaccounts/save',
    GET_BY_ID: (id: number | string) => `/chartofaccounts/get/${id}`,
    DELETE: '/chartofaccounts/delete',
  },
  VOUCHER: {
    GET_GRID: '/vouchers/get-grid-data',
    GET_BY_ID: (id: number | string) => `/vouchers/get/${id}`,
    CREATE: '/vouchers/create',
    REVERSE: (id: number | string) => `/vouchers/reverse/${id}`,
  },
  DSR_ATTENDANCE: {
    GET_GRID: '/attendance/get-grid-data',
    GET_GRID_SUPER: '/attendance/get-grid-data-super',
    GET_BY_ID: (id: number | string) => `/attendance/get/${id}`,
    SAVE: '/attendance/save',
    DELETE: (id: number | string) => `/attendance/delete/${id}`,
  },
  DSR_COLLECTION: {
    GET_GRID: '/collection/get-grid-data',
    GET_GRID_SUPER: '/collection/get-grid-data-super',
    GET_BY_ID: (id: number | string) => `/collection/get/${id}`,
    SAVE: '/collection/save',
    DELETE: (id: number | string) => `/collection/delete/${id}`,
  },
  DSR_DAILY_SALES: {
    GET_GRID: '/dailysales/get-grid-data',
    GET_GRID_SUPER: '/dailysales/get-grid-data-super',
    GET_BY_ID: (id: number | string) => `/dailysales/get/${id}`,
    SAVE: '/dailysales/save',
    DELETE: (id: number | string) => `/dailysales/delete/${id}`,
  },
  DSR_EXPENSE: {
    GET_GRID: '/expense/get-grid-data',
    GET_GRID_SUPER: '/expense/get-grid-data-super',
    GET_BY_ID: (id: number | string) => `/expense/get/${id}`,
    SAVE: '/expense/save',
    DELETE: (id: number | string) => `/expense/delete/${id}`,
  },
  DSR_TARGET: {
    GET_GRID: '/target/get-grid-data',
    GET_GRID_SUPER: '/target/get-grid-data-super',
    GET_BY_ID: (id: number | string) => `/target/get/${id}`,
    SAVE: '/target/save',
    DELETE: (id: number | string) => `/target/delete/${id}`,
  },
  DSR_VISIT: {
    GET_GRID: '/visit/get-grid-data',
    GET_GRID_SUPER: '/visit/get-grid-data-super',
    GET_BY_ID: (id: number | string) => `/visit/get/${id}`,
    SAVE: '/visit/save',
    DELETE: (id: number | string) => `/visit/delete/${id}`,
  },
  FINANCIAL_YEAR: {
    GET_ALL: '/FinancialYear/GetAll',
    GET_BY_ID: (id: number | string) => `/FinancialYear/Get/${id}`,
    SAVE: '/FinancialYear/SaveFinancialYear',
    REMOVE: (id: number | string) => `/FinancialYear/RemoveFinancialYear/${id}`,
    GET_GENERATE_PERIODS: '/FinancialYear/GetGenerateChildList',
  },
  NOTIFICATION: {
    GET_COUNT_AND_LIST: '/Notification/GetNotificationCountAndList',
    GET_LIST: '/Notification/GetNotificationList',
    GET_COUNT_AND_LIST_NFA: '/Notification/GetNotificationCountAndListForNFA',
    GET_LIST_NFA: '/Notification/GetNotificationListForNFA',
    GET_LIST_FOR_NOTIFICATION: '/Notification/GetNotificationListForNotification',
    GET_AP_TYPE_LIST: '/Notification/GetAPTypeList',
    GET_BY_AP_TYPE: (id: number | string) => `/Notification/GetNotificationByAPType/${id}`,
  },
} as const;
