export const API_MODULES = {
  AUTH: '/auth',
  USERS: '/users',
  PAYMENT: '/payment',
  SCM: '/scm',
  STORAGE: '/storage',
  FINANCE: '/finance',
  MAIL: '/mail',
};

const MENU_BASE = '/menu';
const RULE_BASE = '/securityrule';
const GROUP_BASE = '/securitygroup';
const COMBO_BASE = '/combo';
const SYSTEM_VARIABLE_BASE = '/systemvariable';
const COMPANY_BASE = '/company';
const COMMON_BASE = '/common';
const AUDIT_LOG_BASE = '/auditlog';
const SECURITY_CACHE_BASE = '/SecurityCache';

export const API_ENDPOINTS = {
  SYSTEM_CONFIGURATION: {
    GET: (companyId: string) => `/systemconfiguration/get/${companyId}`,
    SAVE: '/systemconfiguration/save-system-configuration',
  },
  MENU: {
    GET_ALL: `${MENU_BASE}/get-all`,
    GET_BY_TYPE: (type: string) => `${MENU_BASE}/get-by-menu-type/${type}`,
    GET_BY_TYPE_AND_COMPANY: (type: string, companyId: string) => `${MENU_BASE}/get-by-menu-type/${type}/${companyId}`,
    SAVE: `${MENU_BASE}/save`,
    REORDER: `${MENU_BASE}/reorder`,
    DELETE: `${MENU_BASE}/delete`,
    GET_LAST_ID: `${MENU_BASE}/get-last-menuid`,
    GET_API_PATH: (id: number) => `${MENU_BASE}/get-api-path/${id}`,
    GET_LOGIN_MENUS: `${MENU_BASE}/get-login-menus`,
    COPY: `${MENU_BASE}/copy`,
  },
  SECURITY_RULE: {
    GET_GRID: `${RULE_BASE}/get-grid-data`,
    GET_GRID_SUPER: `${RULE_BASE}/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `${RULE_BASE}/get/${id}`,
    SAVE: `${RULE_BASE}/save`,
    SAVE_SUPER: `${RULE_BASE}/save-super`,
    GET_PERMISSIONS: (id: number | string) => `${RULE_BASE}/get-permission-list/${id}`,
    // Function returning string for superuser permissions
    GET_PERMISSIONS_SUPER: (id: number | string, companyId: string) => `${RULE_BASE}/get-permission-list-super/${id}/${companyId}`,
    DELETE: (id: number | string) => `${RULE_BASE}/delete/${id}`,
  },
  SECURITY_GROUP: {
    GET_GRID: `${GROUP_BASE}/get-grid-data`,
    GET_GRID_SUPER: `${GROUP_BASE}/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `${GROUP_BASE}/get/${id}`,
    SAVE: `${GROUP_BASE}/save`,
    SAVE_SUPER: `${GROUP_BASE}/save-super`,
    DELETE: (id: number | string) => `${GROUP_BASE}/delete/${id}`
  },
  COMBO: {
    GET_RULES: `${COMBO_BASE}/get-rules`,
    GET_GROUPS: `${COMBO_BASE}/get-groups`,
    GET_RULES_SUPER: (companyId: string) => `${COMBO_BASE}/get-rules-super/${companyId}`,
    GET_GROUPS_SUPER: (companyId: string) => `${COMBO_BASE}/get-groups-super/${companyId}`,
    GET_COMPANIES: `${COMBO_BASE}/get-companies`,
    GET_PARENT_COMPANIES: `${COMBO_BASE}/get-parent-company`,
    GET_ALL_COMPANIES: `${COMBO_BASE}/get-all-company`,
    GET_SYSTEM_VARIABLES: (category: string) => `${COMBO_BASE}/get-systemvariables/${category}`,
    GET_DEFAULT_MENUS: `${COMBO_BASE}/get-default-menus`,
    GET_DEFAULT_MENUS_SUPER: (companyId: string) => `${COMBO_BASE}/get-default-menus-super/${companyId}`,
    GET_DIVISIONS: `${COMBO_BASE}/get-division`,
    GET_DIVISIONS_SUPER: `${COMBO_BASE}/get-division-super`,
    GET_DISTRICTS: `${COMBO_BASE}/get-district`,
    GET_DISTRICTS_SUPER: `${COMBO_BASE}/get-district-super`,
    GET_DISTRICTS_BY_DIVISION: (divisionId: string | number) => `${COMBO_BASE}/get-district-by-division/${divisionId}`,
    GET_THANAS: `${COMBO_BASE}/get-thana`,
    GET_THANAS_SUPER: `${COMBO_BASE}/get-thana-super`,
    GET_THANAS_BY_DISTRICT: (districtId: string | number) => `${COMBO_BASE}/get-thana-by-district/${districtId}`,
    GET_USER_TYPES: `${COMBO_BASE}/get-user-type`,
  },
  COMPANY: {
    GET_GRID: `${COMPANY_BASE}/get-grid-data`,
    GET_BY_ID: (id: number | string) => `${COMPANY_BASE}/get/${id}`,
    SAVE: `${COMPANY_BASE}/save`,
    DELETE: (id: number | string) => `${COMPANY_BASE}/delete/${id}`,
    GET_COMBO: `${COMPANY_BASE}/get-combo`,
  },
  USER: {
    GET_GRID: `/user/get-grid-data`,
    GET_GRID_SUPER: `/user/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/user/get-user/${id}`,
    GET_BY_ID_SUPER: (id: number | string) => `/user/get-user-super/${id}`,
    SAVE: `/user/register`,
    CREATE_SUPER: `/user/create-user`,
    CHANGE_PASSWORD: `/user/change-password`,
    DELETE: (id: number | string) => `/user/delete/${id}`,
  },
  SYSTEM_VARIABLE: {
    GET_GRID: `${SYSTEM_VARIABLE_BASE}/get-grid-data`,
    GET_GRID_SUPER: `${SYSTEM_VARIABLE_BASE}/get-grid-data-super`,
    SAVE: `${SYSTEM_VARIABLE_BASE}/save`,
    SAVE_SUPER: `${SYSTEM_VARIABLE_BASE}/save-super`,
    DELETE: (id: number | string) => `${SYSTEM_VARIABLE_BASE}/delete/${id}`,
  },
  DIVISION: {
    GET_GRID: `/division/get-grid-data`,
    GET_GRID_SUPER: `/division/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/division/get/${id}`,
    SAVE: `/division/save`,
    DELETE: (id: number | string) => `/division/delete/${id}`,
  },
  DISTRICT: {
    GET_GRID: `/district/get-grid-data`,
    GET_GRID_SUPER: `/district/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/district/get/${id}`,
    SAVE: `/district/save`,
    DELETE: (id: number | string) => `/district/delete/${id}`,
  },
  THANA: {
    GET_GRID: `/thana/get-grid-data`,
    GET_GRID_SUPER: `/thana/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/thana/get/${id}`,
    SAVE: `/thana/save`,
    DELETE: (id: number | string) => `/thana/delete/${id}`,
  },
  COMMON: {
    GET_USER_LOG_GRID: `${COMMON_BASE}/get-user-log-grid-data`,
    GET_USER_LOG_GRID_SUPER: `${COMMON_BASE}/get-user-log-grid-data-super`,
  },
  AUDIT_LOG: {
    GET_SYSTEM_CONFIG: (id: number | string, dataSize?: number) => `${AUDIT_LOG_BASE}/get-system-config-audit/${id}${dataSize ? `/${dataSize}` : ''}`
  },
  SECURITY_CACHE: {
    SUMMARY: `${SECURITY_CACHE_BASE}/summary`,
    LIST: (entityType: string) => `${SECURITY_CACHE_BASE}/${entityType}/list`,
    GET_BY_ID: (entityType: string, id: string | number) => `${SECURITY_CACHE_BASE}/${entityType}/${id}`,
    CLEAR: (entityType: string) => `${SECURITY_CACHE_BASE}/${entityType}/clear`,
    EVICT: (entityType: string, id: string | number) => `${SECURITY_CACHE_BASE}/${entityType}/${id}/evict`,
    RELOAD: (entityType: string) => `${SECURITY_CACHE_BASE}/${entityType}/reload`,
  },
  KYC: {
    OCR: '/kyc/ocr',
    SUBMIT: '/kyc/submit',
  },
  GLOBAL_SETTING: {
    ALL: '/global-setting/all',
    GET: (key: string) => `/global-setting/${key}`,
    SAVE: '/global-setting/save',
  },
  USER_SETTING: {
    GET: (userId: number, key: string) => `/user-setting/${userId}/${key}`,
    SAVE: '/user-setting/save',
  },
  WAREHOUSE: {
    GET_GRID: `/warehouse/get-grid-data`,
    GET_GRID_SUPER: `/warehouse/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/warehouse/get/${id}`,
    SAVE: `/warehouse/save`,
    SAVE_SUPER: `/warehouse/save-super`,
    DELETE: (id: number | string) => `/warehouse/delete/${id}`,
  },
  STORAGE: {
    UPLOAD: '/Storage/upload',
    DOWNLOAD: (fileKey: string) => `/Storage/download/${fileKey}`,
    DELETE: (fileKey: string) => `/Storage/delete/${fileKey}`,
  },
  CATEGORY: {
    GET_GRID: `/product/get-category-grid-data`,
    GET_GRID_SUPER: `/product/get-category-grid-data-super`,
    GET_ALL: `/product/get-all-categories`,
    GET_COMBO: `/product/get-category-combo`,
    GET_BY_ID: (id: number | string) => `/product/get-category/${id}`,
    SAVE: `/product/save-category`,
    SAVE_SUPER: `/product/save-category-super`,
    DELETE: (id: number | string) => `/product/delete-category/${id}`,
  },
  BRAND: {
    GET_GRID: `/brand/get-grid-data`,
    GET_COMBO: `/brand/get-combo`,
    GET_BY_ID: (id: number | string) => `/brand/get/${id}`,
    SAVE: `/brand/save`,
    DELETE: (id: number | string) => `/brand/delete/${id}`,
  },
  UNIT: {
    GET_GRID: `/unit/get-grid-data`,
    GET_COMBO: `/combo/get-unit-combo`,
    GET_BY_ID: (id: number | string) => `/unit/get/${id}`,
    SAVE: `/unit/save`,
    DELETE: (id: number | string) => `/unit/delete/${id}`,
  },
  PRODUCT: {
    GET_GRID: `/product/get-grid-data`,
    GET_GRID_SUPER: `/product/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/product/get/${id}`,
    SAVE: `/product/save`,
    SAVE_WITH_FILES: `/product/save-with-files`,
    CSV_UPLOAD: `/product/csv-upload`,
    DELETE: (id: number | string) => `/product/delete/${id}`,
    GET_ALL: `/product/get-all`,
  },
  PRODUCT_ATTRIBUTE: {
    GET_COMBO: `/combo/get-attribute-combo`,
    SAVE: `/product/save-attribute`,
    GET_VALUES: (productId: number | string) => `/product/get-attribute-values/${productId}`,
    SAVE_VALUES: `/product/save-attribute-values`,
  },
  PURCHASE_REQUISITION: {
    GET_GRID: `/purchaserequisition/get-grid-data`,
    GET_GRID_SUPER: `/purchaserequisition/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/purchaserequisition/get/${id}`,
    SAVE: `/purchaserequisition/save`,
    DELETE: (id: number | string) => `/purchaserequisition/delete/${id}`,
  },
  PURCHASE_QUOTATION: {
    GET_GRID: `/purchasequotation/get-grid-data`,
    GET_GRID_SUPER: `/purchasequotation/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/purchasequotation/get/${id}`,
    GET_BY_REQUISITION: (reqId: number | string) => `/purchasequotation/get-by-requisition/${reqId}`,
    SAVE: `/purchasequotation/save`,
    DELETE: (id: number | string) => `/purchasequotation/delete/${id}`,
  },
  PURCHASE_ORDER: {
    GET_GRID: `/purchaseorder/get-grid-data`,
    GET_GRID_SUPER: `/purchaseorder/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/purchaseorder/get/${id}`,
    GET_BY_QUOTATION: (qId: number | string) => `/purchaseorder/get-by-quotation/${qId}`,
    SAVE: `/purchaseorder/save`,
    DELETE: (id: number | string) => `/purchaseorder/delete/${id}`,
  },
  SUPPLIER: {
    GET_GRID: `/supplier/get-grid-data`,
    GET_GRID_SUPER: `/supplier/get-grid-data-super`,
    GET_BY_ID: (id: number | string) => `/supplier/get/${id}`,
    SAVE: `/supplier/save`,
    DELETE: (id: number | string) => `/supplier/delete/${id}`,
  },
  FINANCE_COA: {
    GET_COMBO: (type: string) => `/chartofaccounts/get-combo?type=${type}&isTransactional=true`,
  },
  MAIL_CONFIGURATION: {
    SAVE: `/mailconfiguration/save`,
    GET_ACTIVE: `/mailconfiguration/get-active`,
    GET_BY_ID: (id: number | string) => `/mailconfiguration/get/${id}`,
    GET_GRID: `/mailconfiguration/get-grid-data`,
    GET_GRID_SUPER: `/mailconfiguration/get-grid-data-super`,
    GET_ALL: `/mailconfiguration/get-all`,
    DELETE: (id: number | string) => `/mailconfiguration/delete/${id}`,
  },
  MAIL_GROUP_SETUP: {
    SAVE: `/mailgroupsetup/save`,
    GET_BY_ID: (id: number | string) => `/mailgroupsetup/get/${id}`,
    GET_GRID: `/mailgroupsetup/get-grid-data`,
    GET_GRID_SUPER: `/mailgroupsetup/get-grid-data-super`,
    GET_ALL: `/mailgroupsetup/get-all`,
    GET_BY_NAME: (name: string) => `/mailgroupsetup/get-by-name/${name}`,
    DELETE: (id: number | string) => `/mailgroupsetup/delete/${id}`,
  },
  MAIL_LOG: {
    ENQUEUE: `/maillog/enqueue`,
    GET_BY_ID: (id: number | string) => `/maillog/${id}`,
    GET_ALL: `/maillog`,
    RETRY: (id: number | string) => `/maillog/retry/${id}`,
    GET_GRID: `/maillog/get-grid-data`,
    GET_GRID_SUPER: `/maillog/get-grid-data-super`,
  },
  MAIL_TEMPLATE: {
    SAVE: `/mailtemplate/save`,
    GET_BY_ID: (id: number | string) => `/mailtemplate/get/${id}`,
    GET_BY_GROUP: (groupId: number | string) => `/mailtemplate/get-by-group/${groupId}`,
    GET_ALL: `/mailtemplate/get-all`,
    DELETE: (id: number | string) => `/mailtemplate/delete/${id}`,
    SEND_TEST: `/mailtemplate/send-test`,
  },
} as const;
